name: Check
on:
  pull_request:
    paths-ignore: [".signatures/cla/**"]
  push:
    branches: [main]
    paths-ignore: [".signatures/cla/**"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install
      - run: deno task check
